### ISSUE TITLE
[es]: Spanish Translation of Readme

### ISSUE THREAD

**Issue by darigovresearch** [darigovresearch/Google-Machine-Learning-Glossary-Flashcards#3]
Would be helpful to have a Spanish translation of the readme to help any Spanish users to improve the Spanish version of the Flashcards

**Comment by Jonakss** [comment]
I have done the traslation to spanish and added a first paragraph to reference others languajes of README.
I will send you a PR.
I hope this helps you. 
Cheers.

**Comment by Jonakss** [comment]
I have done the traslation myself (I didn't use google translate). Some paragraph have a little modification to make it more uderstandable, but the concept and the feeling is there.

**Comment by darigovresearch** [comment]
Thank you for your pull request and for taking the time to translate the work yourself as this will be required for any pull requests to be merged back into the repository. Feedback is now available on your pull request https://github.com/darigovresearch/Google-Machine-Learning-Glossary-Flashcards/pull/11 if you wish to take a look and make the adjustments!

**Comment by darigovresearch** [comment]
Pull request #11 closes this issue, thanks for the PR request Jonathan!

**Comment by Jonakss** [comment]
It was a plasure helping you out.
